---
# tasks file for php
- name: Install PHP 7 with the most common packages
  yum:
   state: present
   update_cache: yes 
   name: 
    - php
  notify: restart Apache
- name: upload index.php file to the remote web directory
  copy:
   src: index.php
   dest: /var/www/html
   owner: ec2-user
   group: ec2-user
